# MATH 70116, Deep Learning
## Autumn 2026
## Lecturer: Tom Hadfield
# Introduction to Pytorch : basic operations

In [1]:
import torch
import numpy as np

In [2]:
import numpy as np
print(np.__version__)
import torch
print(torch.__version__)

2.5.3
2.14.0+cpu


In [3]:
# ensure compatibility of torch and numpy
!pip install "numpy<2"
# !pip install numpy

  Using cached numpy-1.26.4-cp313-cp313-win_amd64.whl
  Attempting uninstall: numpy
    Found existing installation: numpy 2.5.3
    Uninstalling numpy-2.5.3:
      Successfully uninstalled numpy-2.5.3


  You can safely remove it manually.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.4.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
ml-dtypes 0.6.0 requires numpy>=2.0.0, but you have numpy 1.26.4 which is incompatible.
ml-dtypes 0.6.0 requires numpy>=2.1.0; python_version >= "3.13", but you have numpy 1.26.4 which is incompatible.
scipy 1.18.1 requires numpy<2.8,>=2.0.0, but you have numpy 1.26.4 which is incompatible.


## Creating tensors in Pytorch

In [4]:
# from a list
a = [1,2,3]
print(type(a))

t_a = torch.tensor(a)
print(t_a)
print(type(t_a))
print(t_a.shape)

<class 'list'>
tensor([1, 2, 3])
<class 'torch.Tensor'>
torch.Size([3])


In [5]:
# from a numpy array
b = np.array([4,5,6], dtype = np.int32)
t_b = torch.tensor(b)
print(type(b))
print(t_b)
print(t_b.shape)

<class 'numpy.ndarray'>
tensor([4, 5, 6], dtype=torch.int32)
torch.Size([3])


In [6]:
# all ones
t_ones = torch.ones(2,3)
print(t_ones)
print(t_ones.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])


In [7]:
# all zeros
t_zeros = torch.zeros(3,4)
print(t_zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


### reshape a tensor

In [8]:
# reshape

x_np = np.arange(0,8)
print(x_np)

x_t = torch.tensor(x_np)
print(x_t)

x_t_24 = x_t.reshape(2,4)
print(x_t_24)

x_t_1222 = x_t.reshape(1,2,2,2)
print(x_t_1222)
print(x_t_1222.shape)
print(x_t_1222[0].shape)
print(x_t_1222[0,0])
print(x_t_1222[0,0,1,1])

[0 1 2 3 4 5 6 7]
tensor([0, 1, 2, 3, 4, 5, 6, 7])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[[[0, 1],
          [2, 3]],

         [[4, 5],
          [6, 7]]]])
torch.Size([1, 2, 2, 2])
torch.Size([2, 2, 2])
tensor([[0, 1],
        [2, 3]])
tensor(3)


### transpose

In [9]:
t = torch.tensor(np.arange(0,15)).reshape(3,5)
print(t)

t_tr = torch.transpose(t,0,1)
print(t_tr)

t = torch.tensor(np.arange(0,8)).reshape(2,2,2)
print(t)

t_tr = torch.transpose(t,0,2)
print(t_tr)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]])
tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])
tensor([[[0, 4],
         [2, 6]],

        [[1, 5],
         [3, 7]]])


<code>torch.rand</code> generates a tensor filled with random numbers uniformly distributed in the range $[0, 1)$

In [10]:
t = torch.rand(3,4)
print(t)
print(t.sum())

tensor([[0.6547, 0.3310, 0.3109, 0.7998],
        [0.4697, 0.1284, 0.9383, 0.5320],
        [0.1206, 0.6964, 0.8986, 0.4458]])
tensor(6.3262)


<code>torch.normal</code> generates a tensor filled with random numbers from a normal distribution

In [11]:
t2 = torch.normal(mean=0, std=1, size=(5,2))
print(t2)

tensor([[-1.0162,  0.7601],
        [-1.9405,  1.8058],
        [ 1.3364, -0.4119],
        [-0.0929,  0.3945],
        [-1.0012,  1.5111]])


<code>torch.squeeze</code> : remove unnecessary dimensions

In [12]:
t = torch.tensor(np.arange(8)).reshape(1,2,1,4,1)
print(t.shape)
print(t)
t = torch.squeeze(t,2)
print(t.shape)
t = torch.squeeze(t,3)
print(t.shape)
t = torch.squeeze(t,0)
print(t.shape)
print(t)

torch.Size([1, 2, 1, 4, 1])
tensor([[[[[0],
           [1],
           [2],
           [3]]],


         [[[4],
           [5],
           [6],
           [7]]]]])
torch.Size([1, 2, 4, 1])
torch.Size([1, 2, 4])
torch.Size([2, 4])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


convert <code>torch.tensor</code> to <code>np.ndarray</code>

In [13]:
t = torch.tensor(np.arange(0,4)).reshape(2,2)
print(type(t), t.shape)

t_np = t.numpy() # new
# t_np = np.array(t) # old
print(type(t_np), t_np.shape)

<class 'torch.Tensor'> torch.Size([2, 2])
<class 'numpy.ndarray'> (2, 2)


## Applying mathematical operations to tensors

In [14]:
# mean
t = torch.tensor(np.arange(0,12)).reshape(3,4)
print(t)

# in order to use mean(), need to convert int-valued tensor to float
print(torch.mean(t.float(), axis=0)) 
print(torch.mean(t.float(), axis=1))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([4., 5., 6., 7.])
tensor([1.5000, 5.5000, 9.5000])


In [15]:
# sum
t = torch.tensor(np.arange(0,8)).reshape(2,2,2)
print(t)

# in order to use sum(), need to convert int-valued tensor to float
print(torch.sum(t.float(), axis=0)) 
print(torch.sum(t.float(), axis=1))
print(torch.sum(t.float(), axis=2))

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])
tensor([[ 4.,  6.],
        [ 8., 10.]])
tensor([[ 2.,  4.],
        [10., 12.]])
tensor([[ 1.,  5.],
        [ 9., 13.]])


In [16]:
# std
t = torch.tensor(np.arange(0,10)).reshape(2,5)
print(t)

# in order to use std(), need to convert int-valued tensor to float
print(torch.std(t.float(), axis=0)) 
print(torch.std(t.float(), axis=1))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([3.5355, 3.5355, 3.5355, 3.5355, 3.5355])
tensor([1.5811, 1.5811])


In [17]:
# add a scalar to a tensor
t = torch.tensor(np.arange(0,4)).reshape(2,2)
print(t, t.dtype)
t = t + 1.23
print(t, t.dtype)

tensor([[0, 1],
        [2, 3]]) torch.int64
tensor([[1.2300, 2.2300],
        [3.2300, 4.2300]]) torch.float32


In [18]:
# multiply a tensor by a scalar
t = torch.tensor(np.arange(0,6)).reshape(2,3)
print(t)
t = 2 * t
print(t)
t = 1.0 * t
print(t, t.dtype)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 0,  2,  4],
        [ 6,  8, 10]])
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]]) torch.float32


In [19]:
# add two tensors
t1 = torch.tensor(np.arange(0,6)).reshape(2,3)
t2 = torch.rand(2,3)
print(t1)
print(t2)
print(t1 + t2)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0.1770, 0.6841, 0.6239],
        [0.6187, 0.1772, 0.6813]])
tensor([[0.1770, 1.6841, 2.6239],
        [3.6187, 4.1772, 5.6813]])


In [20]:
# multiply two tensors
t1 = torch.tensor(np.arange(0,6)).float().reshape(2,3)
t2 = torch.tensor(np.arange(0,6)).float().reshape(3,2)
print(t1)
print(t2)
print(torch.matmul(t1,t2))

tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])
tensor([[10., 13.],
        [28., 40.]])


In [21]:
# element-wise multiplication
t1 = torch.tensor(np.arange(0,6)).float().reshape(2,3)
print(t1)
print(t1**2)

tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])


In [22]:
# element-wise multiplication
t1 = torch.tensor(np.arange(0,6)).float().reshape(2,3)
print(t1)
t2 = torch.tensor(np.arange(0,6)).reshape(2,3) - 3.0
print(t2)
print(t1*t2)

tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[-3., -2., -1.],
        [ 0.,  1.,  2.]])
tensor([[-0., -2., -2.],
        [ 0.,  4., 10.]])
